### ISSUE TITLE
Erro na criação de evento

### ISSUE THREAD

**Issue by gnumoksha** [CauanCabral/Comitiva#17]
1) As colunas certified_dir, certified, position e certified_description na tabela EventDate não existem, ou seja, nao sao criadas com o migration;

2) Seria mais interessante que estas colunas estivessem na tabela Events;

3) O script events.js deveria utilizar a variavel baseUrl nas linhas 14 e 29;

4) Mesmo criando as tabelas faltantes e corrigindo o script, não é possivel criar o evento. Saida do error.log:

2013-01-20 14:10:28 Error: [CakeException] Requisição inválida.
#0 [internal function]: EventsController->admin_eventDateAdd()
#1 /var/www/mnt/lib/Cake/Controller/Controller.php(485): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/mnt/lib/Cake/Routing/Dispatcher.php(103): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/mnt/lib/Cake/Routing/Dispatcher.php(85): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest), Object(CakeResponse))
#4 /var/www/mnt/lib/Cake/Core/Object.php(97): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse), Array)
#5 /var/www/mnt/Comitiva/View/Events/admin_add.ctp(50): Object->requestAction('/admin/events/e...')
#6 /var/www/mnt/lib/Cake/View/View.php(915): include('/home/tobias/ou...')
#7 /var/www/mnt/lib/Cake/View/View.php(879): View->_evaluate('/home/tobias/ou...', Array)
#8 /var/www/mnt/Comitiva/Plugin/DebugKit/View/DebugView.php(43): View->_render('/home/tobias/ou...', Array)
#9 /var/www/mnt/lib/Cake/View/View.php(470): DebugView->_render('/home/tobias/ou...')
#10 /var/www/mnt/Comitiva/Plugin/DebugKit/View/DebugView.php(82): View->render(NULL, NULL)
#11 /var/www/mnt/lib/Cake/Controller/Controller.php(959): DebugView->render(NULL, NULL)
#12 /var/www/mnt/lib/Cake/Routing/Dispatcher.php(110): Controller->render()
#13 /var/www/mnt/lib/Cake/Routing/Dispatcher.php(85): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest), Object(CakeResponse))
#14 /var/www/mnt/Comitiva/webroot/index.php(96): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}

2013-01-20 14:10:28 Error: [CakeException] Requisição inválida.
#0 [internal function]: EventsController->admin_eventDateAdd()
#1 /var/www/mnt/lib/Cake/Controller/Controller.php(485): ReflectionMethod->invokeArgs(Object(EventsController), Array)
#2 /var/www/mnt/lib/Cake/Routing/Dispatcher.php(103): Controller->invokeAction(Object(CakeRequest))
#3 /var/www/mnt/lib/Cake/Routing/Dispatcher.php(85): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest), Object(CakeResponse))
#4 /var/www/mnt/lib/Cake/Core/Object.php(97): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse), Array)
#5 /var/www/mnt/Comitiva/View/Events/admin_add.ctp(50): Object->requestAction('/admin/events/e...')
#6 /var/www/mnt/lib/Cake/View/View.php(915): include('/home/tobias/ou...')
#7 /var/www/mnt/lib/Cake/View/View.php(879): View->_evaluate('/home/tobias/ou...', Array)
#8 /var/www/mnt/Comitiva/Plugin/DebugKit/View/DebugView.php(43): View->_render('/home/tobias/ou...', Array)
#9 /var/www/mnt/lib/Cake/View/View.php(470): DebugView->_render('/home/tobias/ou...')
#10 /var/www/mnt/Comitiva/Plugin/DebugKit/View/DebugView.php(82): View->render(NULL, NULL)
#11 /var/www/mnt/lib/Cake/Controller/Controller.php(959): DebugView->render(NULL, NULL)
#12 /var/www/mnt/lib/Cake/Routing/Dispatcher.php(110): Controller->render()
#13 /var/www/mnt/lib/Cake/Routing/Dispatcher.php(85): Dispatcher->_invoke(Object(EventsController), Object(CakeRequest), Object(CakeResponse))
#14 /var/www/mnt/Comitiva/webroot/index.php(96): Dispatcher->dispatch(Object(CakeRequest), Object(CakeResponse))
#15 {main}

**Comment by CauanCabral** [comment]
Na hora do almoço vou dar uma olhada nisso para reproduzir o erro.

Faltou incluir essas colunas no Migration @agripinoduarte ?

**Comment by gnumoksha** [comment]
Novidades?

**Comment by agripinoduarte** [comment]
vou verificar isso

**Comment by CauanCabral** [comment]
@tobiasgnu estou adicionando suporte ao Travis em todos os plugins usados pelo Comitiva e em outros que minha empresa disponibiliza aqui no github, e ainda não consegui chegar ao final pra verificar esses pontos, mas realmente faltou disponibilizar as atualizações do BD.

Durante essa semana devo resolver todos esses pontos. Quero aproveitar e dar uma boa limpada no código do sistema e começar a incluir alguns testes. Se for possível, faça um fork dela e mande um pull request com as correções que conseguir fazer, me ajudaria bastante ;]

**Comment by agripinoduarte** [comment]
Adicionei o suporte a criação de modelos de certificados. Adicionei um repositório do Tcpdf como submódulo no diretório Vendors, pois a versão que tinha antes era estática e desatualizada (usava um método deprecated). Basta só atualizar os submódulos e atualizar o Migrations pra criar as tabelas e as colunas novas.

**Comment by gnumoksha** [comment]
Aparentemente o que reportei foi sanado.
